version: "3.8"

services:

  mariadb:
    image: mariadb:10.5
    container_name: casdoor-db
    restart: always
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: casdoor_database
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  casdoor:
    image: casbin/casdoor:latest
    container_name: casdoor
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "10443:10443"
    volumes:
      - ./casdoor/conf:/conf
      - ./casdoor/certs:/certs
    environment:
      DB_NAME: casdoor
      DB_USER: root
      DB_PASSWORD: 123456
      RUNNING_IN_DOCKER: true